version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app_network

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
